#!/usr/bin/env bash

# BASH_SOURCE[0] has the path of the script that is being executed
script_dir=$(dirname "$(realpath "${BASH_SOURCE[0]}")")
echo "script_dir: $script_dir"

dry="0"

# get the filter from the command line
filter=""

# find all scripts in the setup-scripts directory
scripts=$(find $script_dir/setup-scripts -maxdepth 1 -type f)

while [[ $# > 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "Executing: $@"
  if [[ $dry == "1" ]]; then
    return
  fi

  bash "$@"
}

# change to the script directory
pushd $script_dir

# run each script in the setup-scripts directory
for script in $scripts; do
  # if a filter is provided, only run scripts that contain the filter
  if [ -n "$filter" ]; then
    # if the script does not contain the filter, skip it
    if echo "$script" | grep -qv "$filter"; then
      continue
    fi
  fi

  log "Running script: $script"
  execute "$script"
done

# change back to the original directory
popd
