[homebrew.files."homebrew/base.Brewfile"]
target = "~/Brewfile"
type= "template"
append = """
{{ include_template "homebrew/personal.Brewfile" }}
"""

[mise.files]
"mise/personal.config.toml" = "~/.config/mise/config.toml"
